name: Daily Commit

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  make_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Daily empty commit"
          git push
