name: Keep app awake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  curl_request:
    runs-on: ubuntu-latest

    steps:
    - name: Make curl request
      run: curl "https://riichi.streamlit.app/?embedded=true"
